"""update booking table

Revision ID: c3aef4bf2256
Revises: 5a1ad68ef891
Create Date: 2024-04-12 17:39:14.489259

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c3aef4bf2256'
down_revision = '5a1ad68ef891'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'amount_paid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('amount_paid', mysql.DECIMAL(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###
